export const ALERTS__SHOW_ALERT = 'ALERTS__SHOW_ALERT';
export const ALERTS__HIDE_ALERT = 'ALERTS__HIDE_ALERT';

export const USERS__FETCH_USER = 'USERS__FETCH_USER';
export const USERS__FETCH_USER_REQUEST = 'USERS__FETCH_USER_REQUEST';
export const USERS__FETCH_USER_SUCCESS = 'USERS__FETCH_USER_SUCCESS';
export const USERS__FETCH_USER_FAILURE = 'USERS__FETCH_USER_FAILURE';
export const USERS__RESET_USER = 'USERS__RESET_USER';
export const USERS__RESET_USER_SUCCESS = 'USERS__RESET_USER_SUCCESS';
