export const ALERTS__SHOW_ALERT = 'ALERTS__SHOW_ALERT';
export const ALERTS__HIDE_ALERT = 'ALERTS__HIDE_ALERT';

export const MODALS__SHOW_MODAL = 'MODALS__SHOW_MODAL';
export const MODALS__HIDE_MODAL = 'MODALS__HIDE_MODAL';

export const USERS__FETCH_USER = 'USERS__FETCH_USER';
export const USERS__FETCH_USER_REQUEST = 'USERS__FETCH_USER_REQUEST';
export const USERS__FETCH_USER_SUCCESS = 'USERS__FETCH_USER_SUCCESS';
export const USERS__FETCH_USER_FAILURE = 'USERS__FETCH_USER_FAILURE';

export const USERS__LOGOUT_USER = 'USERS__LOGOUT_USER';
export const USERS__LOGOUT_USER_SUCCESS = 'USERS__LOGOUT_USER_SUCCESS';

export const USERS__LOGIN_USER = 'USERS__LOGIN_USER';
export const USERS__LOGIN_USER_REQUEST = 'USERS__LOGIN_USER_REQUEST';
export const USERS__LOGIN_USER_SUCCESS = 'USERS__LOGIN_USER_SUCCESS';
export const USERS__LOGIN_USER_FAILURE = 'USERS__LOGIN_USER_FAILURE';

export const EMPLOYEES__FETCH_EMPLOYEES = 'EMPLOYEES__FETCH_EMPLOYEES';
export const EMPLOYEES__FETCH_EMPLOYEES_REQUEST = 'EMPLOYEES__FETCH_EMPLOYEES_REQUEST';
export const EMPLOYEES__FETCH_EMPLOYEES_SUCCESS = 'EMPLOYEES__FETCH_EMPLOYEES_SUCCESS';
export const EMPLOYEES__FETCH_EMPLOYEES_FAILURE = 'EMPLOYEES__FETCH_EMPLOYEES_FAILURE';

export const EMPLOYEES__FILTER_EMPLOYEE = 'EMPLOYEES__FILTER_EMPLOYEE';

export const EMPLOYEES__REMOVE_EMPLOYEE = 'EMPLOYEES__REMOVE_EMPLOYEE';
export const EMPLOYEES__REMOVE_EMPLOYEE_REQUEST = 'EMPLOYEES__REMOVE_EMPLOYEE_REQUEST';
export const EMPLOYEES__REMOVE_EMPLOYEE_SUCCESS = 'EMPLOYEES__REMOVE_EMPLOYEE_SUCCESS';
export const EMPLOYEES__REMOVE_EMPLOYEE_FAILURE = 'EMPLOYEES__REMOVE_EMPLOYEE_FAILURE';

export const EMPLOYEES__GET_EMPLOYEE = 'EMPLOYEES__GET_EMPLOYEE';
export const EMPLOYEES__GET_EMPLOYEE_REQUEST = 'EMPLOYEES__GET_EMPLOYEE_REQUEST';
export const EMPLOYEES__GET_EMPLOYEE_SUCCESS = 'EMPLOYEES__GET_EMPLOYEE_SUCCESS';
export const EMPLOYEES__GET_EMPLOYEE_FAILURE = 'EMPLOYEES__GET_EMPLOYEE_FAILURE';
export const EMPLOYEES__GET_EMPLOYEE_CLEAR = 'EMPLOYEES__GET_EMPLOYEE_CLEAR';

export const EMPLOYEES__ADD_EMPLOYEE = 'EMPLOYEES__ADD_EMPLOYEE';
export const EMPLOYEES__ADD_EMPLOYEE_REQUEST = 'EMPLOYEES__ADD_EMPLOYEE_REQUEST';
export const EMPLOYEES__ADD_EMPLOYEE_SUCCESS = 'EMPLOYEES__ADD_EMPLOYEE_SUCCESS';
export const EMPLOYEES__ADD_EMPLOYEE_FAILURE = 'EMPLOYEES__ADD_EMPLOYEE_FAILURE';

export const EMPLOYEES__EDIT_EMPLOYEE = 'EMPLOYEES__EDIT_EMPLOYEE';
export const EMPLOYEES__EDIT_EMPLOYEE_REQUEST = 'EMPLOYEES__EDIT_EMPLOYEE_REQUEST';
export const EMPLOYEES__EDIT_EMPLOYEE_SUCCESS = 'EMPLOYEES__EDIT_EMPLOYEE_SUCCESS';
export const EMPLOYEES__EDIT_EMPLOYEE_FAILURE = 'EMPLOYEES__EDIT_EMPLOYEE_FAILURE';
