export const ALERTS__SHOW_ALERT = 'ALERTS__SHOW_ALERT';
export const ALERTS__HIDE_ALERT = 'ALERTS__HIDE_ALERT';

export const USERS__FETCH_USER = 'USERS__FETCH_USER';
export const USERS__FETCH_USER_REQUEST = 'USERS__FETCH_USER_REQUEST';
export const USERS__FETCH_USER_SUCCESS = 'USERS__FETCH_USER_SUCCESS';
export const USERS__FETCH_USER_FAILURE = 'USERS__FETCH_USER_FAILURE';
export const USERS__LOGOUT_USER = 'USERS__LOGOUT_USER';
export const USERS__LOGOUT_USER_SUCCESS = 'USERS__LOGOUT_USER_SUCCESS';
export const USERS__LOGIN_USER = 'USERS__LOGIN_USER';
export const USERS__LOGIN_USER_REQUEST = 'USERS__LOGIN_USER_REQUEST';
export const USERS__LOGIN_USER_SUCCESS = 'USERS__LOGIN_USER_SUCCESS';
export const USERS__LOGIN_USER_FAILURE = 'USERS__LOGIN_USER_FAILURE';

export const EMPLOYEES__FETCH_EMPLOYEES = 'EMPLOYEES__FETCH_EMPLOYEES';
export const EMPLOYEES__FETCH_EMPLOYEES_REQUEST = 'EMPLOYEES__FETCH_EMPLOYEES_REQUEST';
export const EMPLOYEES__FETCH_EMPLOYEES_SUCCESS = 'EMPLOYEES__FETCH_EMPLOYEES_SUCCESS';
export const EMPLOYEES__FETCH_EMPLOYEES_FAILURE = 'EMPLOYEES__FETCH_EMPLOYEES_FAILURE';






/*

export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';



export const EMPLOYEES_CHANGE_CURRENT_PAGE = 'EMPLOYEES_CHANGE_CURRENT_PAGE';

export const EMPLOYEES_GET_REQUEST = 'EMPLOYEES_GET_REQUEST';
export const EMPLOYEES_GET_SUCCESS = 'EMPLOYEES_GET_SUCCESS';
export const EMPLOYEES_GET_FAILURE = 'EMPLOYEES_GET_FAILURE';
export const EMPLOYEES_GET_CLEAR = 'EMPLOYEES_GET_CLEAR';

export const EMPLOYEES_ADD_REQUEST = 'EMPLOYEES_ADD_REQUEST';
export const EMPLOYEES_ADD_SUCCESS = 'EMPLOYEES_ADD_SUCCESS';
export const EMPLOYEES_ADD_FAILURE = 'EMPLOYEES_ADD_FAILURE';

export const EMPLOYEES_EDIT_REQUEST = 'EMPLOYEES_EDIT_REQUEST';
export const EMPLOYEES_EDIT_SUCCESS = 'EMPLOYEES_EDIT_SUCCESS';
export const EMPLOYEES_EDIT_FAILURE = 'EMPLOYEES_EDIT_FAILURE';

export const EMPLOYEES_REMOVE_REQUEST = 'EMPLOYEES_REMOVE_REQUEST';
export const EMPLOYEES_REMOVE_SUCCESS = 'EMPLOYEES_REMOVE_SUCCESS';
export const EMPLOYEES_REMOVE_FAILURE = 'EMPLOYEES_REMOVE_FAILURE';




*/
